server:
  wwwroot: wwwroot
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rainng_oj?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 961523404

oj:
  languages: 'c=0|cpp=1|java=2|python=3'
  dbLanguages: 'mysql=20'
  judger:
    name: OpenJudger
    password: 961523404Azure99GG